/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   precomputed_ranks_bfs.c                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: hnah <hnah@student.42singapore.sg>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/09/30 23:16:55 by hnah              #+#    #+#             */
/*   Updated: 2026/09/30 23:25:10 by hnah             ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "push_swap.h"

/*
** Design, function template and two-moves-per-byte proposal: hnah.
** AI supplied the Python generator, bit arithmetic and hex notation advice.
** Only table bytes are generated by debug/generate_precomputed_sample.py.
** Three bytes per solution; see README for detailed authorship.
*/
static const unsigned char	*encoded_bfs_data(int count, int lehmer_rank)
{
	static const unsigned char	starts[] = {0, 0, 1, 3, 9};
	static const unsigned char	data[] = {
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x91, 0x00, 0x00, 0x10, 0x00, 0x00,
		0x90, 0x00, 0x00, 0x60, 0x00, 0x00, 0x61, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x59, 0x14, 0x00, 0x51, 0x40, 0x00,
		0x91, 0x00, 0x00, 0x16, 0x00, 0x00, 0x56, 0x14, 0x00,
		0x10, 0x00, 0x00, 0x59, 0x14, 0x10, 0x51, 0x41, 0x00,
		0x90, 0x00, 0x00, 0x16, 0x10, 0x00, 0x19, 0x16, 0x00,
		0x15, 0x14, 0x00, 0x19, 0x10, 0x00, 0x15, 0x14, 0x10,
		0x19, 0x00, 0x00, 0x66, 0x00, 0x00, 0x66, 0x10, 0x00,
		0x60, 0x00, 0x00, 0x91, 0x61, 0x00, 0x61, 0x00, 0x00,
		0x91, 0x60, 0x00, 0x16, 0x60, 0x00, 0x16, 0x61, 0x00,
	};

	return (data + (starts[count] + lehmer_rank) * 3);
}

/* High nibble first; zero ends the answer; 1..11 map to move codes. */
static int	decode_bfs_data(t_soln *x, const unsigned char *packed)
{
	static const char	moves[] = "0123456789AB";
	int					i;
	int					move;

	i = 0;
	while (i < 6)
	{
		move = (packed[i / 2] >> ((1 - i % 2) * 4)) & 15;
		if (move == 0)
			return (SUCCESS);
		if (move > 11 || x->step >= MAX_MOVES_CONSIDERED)
			return (ERROR);
		append_move_to_soln(x, moves[move]);
		i++;
	}
	return (ERROR);
}

/*
** Call after new_soln_init: empty answer slot, empty B, ranks 0..count-1.
** Record the answer only; A is unchanged. The answer slot belongs to x.
** Setting split to zero reuses calculate_state_id as a permutation-only rank.
*/
int	get_precomputed_bfs(t_soln *x, t_circle_buf *a, int count)
{
	t_brutestate	state;
	int				i;
	int				value;

	if (!x || !a || count < 1 || count > 4 || cbuf_len(a) != count)
		return (ERROR);
	if (!x->ans || !x->ans_len || x->cur < 0 || x->step != 0)
		return (ERROR);
	state.split = 0;
	i = 0;
	while (i < count)
	{
		if (cbuf_read_at(a, i, &value) == ERROR)
			return (ERROR);
		state.value[i] = value;
		i++;
	}
	return (decode_bfs_data(x,
			encoded_bfs_data(count, calculate_state_id(&state, count))));
}
