#!/usr/bin/env python3
"""Check packed bytes, every sample solution, optimality and wrapped buffers."""
from itertools import permutations
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'debug'))
from generate_precomputed_sample import MOVES, packed_data, solutions

HARNESS = r'''
#include "push_swap.h"
#include <string.h>

int main(int argc, char **argv)
{
    circle_buf a, b, stacks[2], before;
    soln x;
    int n = argc - 1;
    memset(&a, 0, sizeof(a));
    memset(&b, 0, sizeof(b));
    cbuf_init_ab(&a, &b, n);
    a.read_idx = n;
    a.write_idx = (n + n) % a.capacity;
    for (int i = 0; i < n; ++i)
        a.buf[(a.read_idx + i) % a.capacity] = atoi(argv[i + 1]);
    if (soln_init(&x, 1, MAX_MOVES_CONSIDERED)
        || new_soln_init(&x, stacks, &a, &b))
        return 1;
    before = stacks[A];
    if (get_precomputed_bfs(&x, &stacks[A], n)
        || x.step != x.ans_len[x.cur]
        || memcmp(&before, &stacks[A], sizeof(before))
        || print_best_soln(&x))
        return 2;
    ryker_ft_free_str_array(x.ans);
    free(x.ans_len);
    return 0;
}
'''


def main():
    subprocess.run(['make', '-s', '-j4'], cwd=ROOT, check=True)
    source = (ROOT / 'src/sorting_algorithms/Exact_hardcoded/precomputed_ranks_bfs.c').read_text()
    actual = bytes(int(h, 16) for h in re.findall(r'\\x([0-9a-f]{2})', source))
    assert actual == packed_data(), 'C initializer differs from reverse BFS'
    total = 0
    with tempfile.TemporaryDirectory(prefix='push_swap_precomputed_') as folder:
        path = Path(folder)
        (path / 'harness.c').write_text(HARNESS)
        objects = [str(p) for p in (ROOT / 'obj').rglob('*.o')
                   if p.name != 'main_push_swap.o']
        subprocess.run(['cc', '-Wall', '-Wextra', '-Werror', '-I', str(ROOT / 'includes'),
                        str(path / 'harness.c'), *objects, str(ROOT / 'libft/libft.a'),
                        '-o', str(path / 'harness')], check=True)
        for n in range(1, 5):
            expected = solutions(n)
            for rank, values in enumerate(permutations(range(n))):
                args = list(map(str, values))
                for binary in (path / 'harness', ROOT / 'push_swap'):
                    run = subprocess.run([str(binary), *args], capture_output=True,
                                         timeout=10, check=True)
                    moves = run.stdout.decode().splitlines()
                    assert len(moves) == len(expected[rank]), (values, moves)
                    assert all(move in MOVES for move in moves)
                    checked = subprocess.run([str(ROOT / 'tests/checker_linux'), *args],
                                             input=run.stdout, capture_output=True,
                                             timeout=5, check=True)
                    assert checked.stdout.strip() == b'OK', (values, checked.stdout)
                total += 1
        for values in ((4, 1, 3, 0, 2),):
            args = list(map(str, values))
            run = subprocess.run([str(ROOT / 'push_swap'), *args], capture_output=True,
                                 timeout=10, check=True)
            checked = subprocess.run([str(ROOT / 'tests/checker_linux'), *args],
                                     input=run.stdout, capture_output=True, check=True)
            assert checked.stdout.strip() == b'OK', 'BFS fallback failed'
    print(f'PASS: {total} permutations, optimal lengths, checker, wrapped buffers, '
          'generated bytes and n=5 fallback')


if __name__ == '__main__':
    main()
